---
booktitle: Proceedings of the Third Teaching Machine Learning and Artificial Intelligence
  Workshop
shortname: TeachML
year: '2022'
volume: '207'
start: 2022-09-19
end: 2022-09-23
published: 2023-12-02
conference_number: '03'
layout: proceedings
series: Proceedings of Machine Learning Research
publisher: PMLR
issn: 2640-3498
id: TeachML-2022
month: 0
cycles: false
bibtex_editor: Kinnaird, Katherine M. and Steinbach, Peter and Guhr, Oliver
editor:
- given: Katherine M.
  family: Kinnaird
- given: Peter
  family: Steinbach
- given: Oliver
  family: Guhr
title: Proceedings of Machine Learning Research
description: |
  Proceedings of the Third Teaching Machine Learning and Artificial Intelligence Workshop
    Held in Grenoble, France and online on 19-23 September 2022

  Published as Volume 207 by the Proceedings of Machine Learning Research on 02 December 2023.

  Volume Edited by:
    Katherine M. Kinnaird
    Peter Steinbach
    Oliver Guhr

  Series Editors:
    Neil D. Lawrence
date_str: 19--23 Sep
url: https://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v207"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: mlresearch/jekyll-theme
style: pmlr
permalink: "/:title.html"
ghub:
  edit: true
  repository: v207
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
volume_type: Volume
volume_dir: v207
email: ''
conference:
  name: The Third Teaching Machine Learning and Artificial Intelligence Workshop
  url: https://teaching-ml.github.io/2022/
  location: Grenoble, France and online
  dates:
  - 2022-09-19
  - 2022-09-20
  - 2022-09-21
  - 2022-09-22
  - 2022-09-23
analytics:
  google:
    tracking_id: UA-92432422-1
orig_bibfile: "/Users/neil/mlresearch/v207/teachml22.bib"
# Site settings
# Original source:  /Users/neil/mlresearch/v207/teachml22.bib
